// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: AddressBook.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Contact : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"id")]
    public int Id { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"email")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Email
    {
        get { return __pbn__method.Is(3) ? ((string)__pbn__method.Object) : ""; }
        set { __pbn__method = new global::ProtoBuf.DiscriminatedUnion32Object(3, value); }
    }
    public bool ShouldSerializeEmail() => __pbn__method.Is(3);
    public void ResetEmail() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__method, 3);

    private global::ProtoBuf.DiscriminatedUnion32Object __pbn__method;

    [global::ProtoBuf.ProtoMember(4, Name = @"phone")]
    public int Phone
    {
        get { return __pbn__method.Is(4) ? __pbn__method.Int32 : default; }
        set { __pbn__method = new global::ProtoBuf.DiscriminatedUnion32Object(4, value); }
    }
    public bool ShouldSerializePhone() => __pbn__method.Is(4);
    public void ResetPhone() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__method, 4);

    [global::ProtoBuf.ProtoMember(5, Name = @"contactable")]
    public bool Contactable
    {
        get { return __pbn__method.Is(5) ? __pbn__method.Boolean : default; }
        set { __pbn__method = new global::ProtoBuf.DiscriminatedUnion32Object(5, value); }
    }
    public bool ShouldSerializeContactable() => __pbn__method.Is(5);
    public void ResetContactable() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__method, 5);

}

[global::ProtoBuf.ProtoContract()]
public partial class AddressBook : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"contact")]
    public global::System.Collections.Generic.List<Contact> Contacts { get; } = new global::System.Collections.Generic.List<Contact>();

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
